== Projects and tasks

 project 和task 是gradle的两个基本概念

== Hello world

build.gradle
----
task hello {
    doLast {
        println 'Hello world!'
    }
}
----
gradle -q hello

== A shortcut task definition

build.gradle
----
task hello << {
    println 'Hello world!'
}
----

== Build scripts are code

build.gradle
----
task upper << {
    String someString = 'mY_nAmE'
    println "Original: " + someString 
    println "Upper case: " + someString.toUpperCase()
}
----

----
task count << {
    4.times { print "$it " }
}
----
== Task dependencies
----
task hello << {
    println 'Hello world!'
}
task intro(dependsOn: hello) << {
    println "I'm Gradle"
}

----
gradle intro
---- 
task taskX(dependsOn: 'taskY') << {
    println 'taskX'
}
task taskY << {
    println 'taskY'
}

----

gradle taskX


== Dynamic tasks

 dynamic create tasks

----
build.gradle
4.times { counter ->
    task "task$counter" << {
        println "I'm task number $counter"
    }
}
----

gradle task0

== Manipulating existing tasks


----
4.times { counter ->
    task "task$counter" << {
        println "I'm task number $counter"
    }
}
task0.dependsOn task2, task3

----


 Accessing a task via API - adding behaviour

----
task hello << {
    println 'Hello Earth'
}
hello.doFirst {
    println 'Hello Venus'
}
hello.doLast {
    println 'Hello Mars'
}
hello << {
    println 'Hello Jupiter'
}

----

gradle -q hello

== Shortcut notations

----
task hello << {
    println 'Hello world!'
}
hello.doLast {
    println "Greetings from the $hello.name task."
}
----

== Extra task properties

 You can add your own properties to a task.

----
task myTask {
    ext.myProperty = "myValue"
}

task printTaskProperties << {
    println myTask.myProperty
}

----

 gradle -q printTaskProperties

== Using Ant Tasks

----
task loadfile << {
    def files = file('../antLoadfileResources').listFiles().sort()
    files.each { File file ->
        if (file.isFile()) {
            ant.loadfile(srcFile: file, property: file.name)
            println " *** $file.name ***"
            println "${ant.properties[file.name]}"
        }
    }
}

----

gradle -q loadfile

== Using methods

Using methods to organize your build logic
----
task checksum << {
    fileList('../antLoadfileResources').each {File file ->
        ant.checksum(file: file, property: "cs_$file.name")
        println "$file.name Checksum: ${ant.properties["cs_$file.name"]}"
    }
}

task loadfile << {
    fileList('../antLoadfileResources').each {File file ->
        ant.loadfile(srcFile: file, property: file.name)
        println "I'm fond of $file.name"
    }
}

File[] fileList(String dir) {
    file(dir).listFiles({file -> file.isFile() } as FileFilter).sort()
}
---- 
gradle -q loadfile

== Default tasks

----
defaultTasks 'clean', 'run'

task clean << {
    println 'Default Cleaning!'
}

task run << {
    println 'Default Running!'
}

task other << {
    println "I'm not a default task!"
}
----

----
gradle -q
Default Cleaning!
Default Running!
----

This is equivalent to running gradle clean run. In a multi-project build every subproject can have its own specific default tasks. If a subproject does not specify default tasks, the default tasks of the parent project are used (if defined).

== Configure by DAG

Gradle has a configuration phase and an execution phase.

----
task distribution << {
    println "We build the zip with version=$version"
}

task release(dependsOn: 'distribution') << {
    println 'We release now'
}

gradle.taskGraph.whenReady {taskGraph ->
    if (taskGraph.hasTask(release)) {
        version = '1.0'
    } else {
        version = '1.0-SNAPSHOT'
    }
}
----

task dependsOn
access task with API
extra properties
default tasks
configure by DAG
