==  Defining tasks

build.gradle
----
task(hello) << {
    println "hello"
}

task(copy, type: Copy) {
    from(file('srcDir'))
    into(buildDir)
}
----

build.gradle

----
task('hello') <<
{
    println "hello"
}

task('copy', type: Copy) {
    from(file('srcDir'))
    into(buildDir)
}
----

build.gradle

----
tasks.create(name: 'hello') << {
    println "hello"
}

tasks.create(name: 'copy', type: Copy) {
    from(file('srcDir'))
    into(buildDir)
}
----

== Locating tasks

build.gradle

----
task hello

println hello.name
println project.hello.name

----

build.gradle
----
task hello

println tasks.hello.name
println tasks['hello'].name
----

build.gradle
----
project(':projectA') {
    task hello
}

task hello

println tasks.getByPath('hello').path
println tasks.getByPath(':hello').path
println tasks.getByPath('projectA:hello').path
println tasks.getByPath(':projectA:hello').path
----


== Configuring tasks

copy task

----
task myCopy(type: Copy)
----

build.gradle
----
Copy myCopy = task(myCopy, type: Copy)
myCopy.from 'resources'
myCopy.into 'target'
myCopy.include('**/*.txt', '**/*.xml', '**/*.properties')
----

config task with closure
----
task myCopy(type: Copy)
myCopy {
   from 'resources'
   into 'target'
   include('**/*.txt', '**/*.xml', '**/*.properties')
}

----

define a task with closure

----
task copy(type: Copy) {
   from 'resources'
   into 'target'
   include('**/*.txt', '**/*.xml', '**/*.properties')
}
----


== Adding dependencies to a task

 Adding dependency on task from another projec

----
project('projectA') {
    task taskX(dependsOn: ':projectB:taskY') << {
        println 'taskX'
    }
}

project('projectB') {
    task taskY << {
        println 'taskY'
    }
}
----

adding dependency using task object

----
task taskX << {
    println 'taskX'
}

task taskY << {
    println 'taskY'
}

taskX.dependsOn taskY
----

Adding dependency using closure
----
task taskX << {
    println 'taskX'
}

taskX.dependsOn {
    tasks.findAll { task -> task.name.startsWith('lib') }
}

task lib1 << {
    println 'lib1'
}

task lib2 << {
    println 'lib2'
}

task notALib << {
    println 'notALib'
}
----

== Ordering tasks

There are two ordering rules available: “must run after” and “should run after”.

adding a 'must run after' task ordering
----
task taskX << {
    println 'taskX'
}
task taskY << {
    println 'taskY'
}
taskY.mustRunAfter taskX
----

Adding a 'should run after' task ordering
----
task taskX << {
    println 'taskX'
}
task taskY << {
    println 'taskY'
}
taskY.shouldRunAfter taskX
----

== Adding a description to a task

build.gradle
----
task copy(type: Copy) {
   description 'Copies the resource directory to the target directory.'
   from 'resources'
   into 'target'
   include('**/*.txt', '**/*.xml', '**/*.properties')
}
----


== Replacing tasks

overwriting a task
----
task copy(type: Copy)

task copy(overwrite: true) << {
    println('I am the new one.')
}
----

== Skipping tasks

=== Using a predicate

Skipping a task using a predicate

----
task hello << {
    println 'hello world'
}

hello.onlyIf { !project.hasProperty('skipHello') }
----

=== Using StopExecutionException

Skipping tasks with StopExecutionException
----
task compile << {
    println 'We are doing the compile.'
}

compile.doFirst {
    // Here you would put arbitrary conditions in real life.
    // But this is used in an integration test so we want defined behavior.
    if (true) { throw new StopExecutionException() }
}
task myTask(dependsOn: 'compile') << {
   println 'I am not affected'
}


----


=== Enabling and disabling tasks

 Enabling and disabling tasks

----
task disableMe << {
    println 'This should not be printed if the task is disabled.'
}
disableMe.enabled = false

----


== Skipping tasks that are up-to-date

=== Declaring a task's inputs and outputs



== Task rules


----
tasks.addRule("Pattern: ping<ID>") { String taskName ->
    if (taskName.startsWith("ping")) {
        task(taskName) << {
            println "Pinging: " + (taskName - 'ping')
        }
    }
}
----

----
tasks.addRule("Pattern: ping<ID>") { String taskName ->
    if (taskName.startsWith("ping")) {
        task(taskName) << {
            println "Pinging: " + (taskName - 'ping')
        }
    }
}

task groupPing {
    dependsOn pingServer1, pingServer2
}

----

== Finalizer tasks


Finalizer tasks are automatically added to the task graph when the finalized task is scheduled to run.

----
task taskX << {
    println 'taskX'
}
task taskY << {
    println 'taskY'
}

taskX.finalizedBy taskY
----

----
task taskX << {
    println 'taskX'
    throw new RuntimeException()
}
task taskY << {
    println 'taskY'
}

taskX.finalizedBy taskY

----


````
task 管理
顺序，enable/disable，skip task,Finalizer
