
build.gradle
----
task compile << {
    println 'compiling source'
}

task compileTest(dependsOn: compile) << {
    println 'compiling unit tests'
}

task test(dependsOn: [compile, compileTest]) << {
    println 'running unit tests'
}

task dist(dependsOn: [compile, test]) << {
    println 'building the distribution'
}
----

== Executing multiple tasks

 gradle dist test

== exclude tasks

 -x
----
gradle dist -x test
----

exclude task test

== Continuing the build when a failure occurs

 --continue

== Task name abbreviation

----
gradle di
gradle cT
----

== Selecting which build to execute

 -b option to select another build file
 -p option to specify the project directory to use
 For multi-project builds you should use -p option instead of -b option.

----
 gradle -q -b subdir/myproject.gradle hello
 gradle -q -p subdir hello
----


== Obtaining information about your build

 Gradle provides several built-in tasks which show particular details of your build

Listing projects

 gradle -q projects

Listing tasks
 
 gradle -q tasks
 gradle -q tasks --all

Show task usage details

 gradle help --task someTask 
 gradle -q help --task libs

Listing project dependencies

 gradle -q dependencies api:dependencies webapp:dependencies

 gradle -q api:dependencies --configuration testCompile

Listing project buildscript dependencies

 gradle buildEnvironment

Getting the insight into a particular dependency

 gradle -q webapp:dependencyInsight --dependency groovy --configuration compile

Listing project properties
 
 gradle -q api:properties

Profiling a build

 --profile

== Dry Run

 gradle -m clean compile


